### ISSUE TITLE
Maintainers wanted!

### ISSUE THREAD

**Issue by rfay** [drud/ddev-mongo#1]
@wtfred - you contributed the original work for this. Would you consider co-maintaining this project?

Anybody else around that regularly uses Mongo? I'm no expert, so having somebody else around who actually knows their way around will help. I can help with everything in the ddev/docker/docker-compose end of course.

**Comment by julienloizelet** [comment]
I guess we can close this one :)

**Comment by tyler36** [comment]
Looks good. Thanks for becoming maintainer and congrats on the `1.0.0` release!

**Comment by rfay** [comment]
Yay!
